### ISSUE TITLE
When the code will be released?

### ISSUE THREAD

**Issue by andypinxinliu** [wanmok/iterx#1]
Hi,

I am really interested in this paper of using imitation for doc-level extraction and congraduations this work is finally accepted by EACL. Would you release the code then?

**Comment by wanmok** [comment]
Thanks for the interest! Yes, we are in the process of releasing the codebase. We plan to release related materials in the following order:

- Model outputs
- Metric implementations
- Model implementation
- Model checkpoints

We are trying to get most of them done in a month. We can ping you back when they are ready (suppose that you are looking for the model implementation).

**Comment by andypinxinliu** [comment]
> Thanks for the interest! Yes, we are in the process of releasing the codebase. We plan to release related materials in the following order:
> 
> 
> 
> - Model outputs
> 
> - Metric implementations
> 
> - Model implementation
> 
> - Model checkpoints
> 
> 
> 
> We are trying to get most of them done in a month. We can ping you back when they are ready (suppose that you are looking for the model implementation). 

Thank you!

**Comment by wanmok** [comment]
> > Thanks for the interest! Yes, we are in the process of releasing the codebase. We plan to release related materials in the following order:
> > 
> > * Model outputs
> > * Metric implementations
> > * Model implementation
> > * Model checkpoints
> > 
> > We are trying to get most of them done in a month. We can ping you back when they are ready (suppose that you are looking for the model implementation).
> 
> Thank you!

Hi, sorry for the delay. We have released both metric and model.
